blank_issues_enabled: false
contact_links:
    - name: ğŸ’¡ Features and ideas
      url: https://github.com/UmbHost/UmbCheckout/discussions/categories/ideas
      about: Start a new discussion when you have ideas or feature requests, eventually discussions can turn into plans
    - name: ğŸ“– Documentation Issue
      url: https://github.com/UmbHost/UmbCheckout-Documentation/issues
      about: Documentation issues should be reported on the UmbCheckout documentation repository.
    - name: ğŸ” Security Issue
      url: https://github.com/UmbHost/UmbCheckout/security/advisories/new
      about: Discovered a Security Issue in UmbCheckout?
