name: Package up.

on:
  workflow_dispatch:
    
jobs:

  build:
    runs-on: windows-latest 

    env:
      CONFIG: 'Release'
      SOLUTION_FILE: './UmbCheckout.sln'
      OUT_FOLDER: './build.out/'

    steps:

    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: "7.0.304"
    
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.7
      with:
        versionSpec: '5.x'    
    
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'
        fetch-depth: 0   
    
    - name: Retrieve cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget-umbcheckout

    - name: Determine Version with GitVersion (MSBuild in Proj will do this)
      id:   gitversion
      uses: gittools/actions/gitversion/execute@v0.9.15
      with:
        useConfigFile: true
        configFilePath: ./GitVersion.yml

    - name: Display GitVersion SemVer
      run: |
       echo "FullSemVer: ${{ steps.gitversion.outputs.fullSemVer }}"
              
# ------------------------
# actual builds / packages 
# ------------------------
    - name: Restore UmbCheckout
      run: dotnet restore ./src/UmbCheckout/UmbCheckout.csproj 

    - name: Restore UmbCheckout.uSync
      run: dotnet restore ./src/UmbCheckout.uSync/UmbCheckout.uSync.csproj

    - name: Restore UmbCheckout.Stripe.uSync
      run: dotnet restore ./src/UmbCheckout.Stripe.uSync/UmbCheckout.Stripe.uSync.csproj

    - name: tests
      run: dotnet test ./src/UmbCheckout.Tests/UmbCheckout.Tests.csproj

    - name: Build UmbCheckout.Core
      run: dotnet pack ./src/UmbCheckout.Core/UmbCheckout.Core.csproj --no-restore -c ${{env.CONFIG}} --output ${{env.OUT_FOLDER}} /p:version=${{steps.gitversion.outputs.fullSemVer}}

    - name: Build UmbCheckout.Shared
      run: dotnet pack ./src/UmbCheckout.Shared/UmbCheckout.Shared.csproj --no-restore -c ${{env.CONFIG}} --output ${{env.OUT_FOLDER}} /p:version=${{steps.gitversion.outputs.fullSemVer}}

    - name: Build UmbCheckout.Stripe
      run: dotnet pack ./src/UmbCheckout.Stripe/UmbCheckout.Stripe.csproj -c ${{env.CONFIG}} --output ${{env.OUT_FOLDER}} /p:version=${{steps.gitversion.outputs.fullSemVer}}

    - name: Build UmbCheckout.Backoffice
      run: dotnet pack ./src/UmbCheckout.Backoffice/UmbCheckout.Backoffice.csproj -c ${{env.CONFIG}} --output ${{env.OUT_FOLDER}} /p:version=${{steps.gitversion.outputs.fullSemVer}}

    - name: Build UmbCheckout.uSync
      run: dotnet pack ./src/UmbCheckout.uSync/UmbCheckout.uSync.csproj --no-restore -c ${{env.CONFIG}} --output ${{env.OUT_FOLDER}} /p:version=${{steps.gitversion.outputs.fullSemVer}}

    - name: Build UmbCheckout.Stripe.uSync
      run: dotnet pack ./src/UmbCheckout.Stripe.uSync/UmbCheckout.Stripe.uSync.csproj --no-restore -c ${{env.CONFIG}} --output ${{env.OUT_FOLDER}} /p:version=${{steps.gitversion.outputs.fullSemVer}}

    - name: Build UmbCheckout
      run: dotnet pack ./src/UmbCheckout/UmbCheckout.csproj --no-restore -c ${{env.CONFIG}} --output ${{env.OUT_FOLDER}} /p:version=${{steps.gitversion.outputs.fullSemVer}}
      
    - name: Push to UmbHost GitHub Nuget Repo
      if: ${{ github.event_name != 'pull_request' }}
      run: | 
        dotnet nuget push ./build.out/UmbCheckout.${{steps.gitversion.outputs.fullSemVer}}.nupkg --skip-duplicate --source https://nuget.pkg.github.com/umbhost/index.json --api-key ${{ github.token }}
        dotnet nuget push ./build.out/UmbCheckout.Core.${{steps.gitversion.outputs.fullSemVer}}.nupkg --skip-duplicate --source https://nuget.pkg.github.com/umbhost/index.json --api-key ${{ github.token }}
        dotnet nuget push ./build.out/UmbCheckout.Shared.${{steps.gitversion.outputs.fullSemVer}}.nupkg --skip-duplicate --source https://nuget.pkg.github.com/umbhost/index.json --api-key ${{ github.token }}
        dotnet nuget push ./build.out/UmbCheckout.Backoffice.${{steps.gitversion.outputs.fullSemVer}}.nupkg --skip-duplicate --source https://nuget.pkg.github.com/umbhost/index.json --api-key ${{ github.token }}
        dotnet nuget push ./build.out/UmbCheckout.Stripe.${{steps.gitversion.outputs.fullSemVer}}.nupkg --skip-duplicate --source https://nuget.pkg.github.com/umbhost/index.json --api-key ${{ github.token }}
        dotnet nuget push ./build.out/UmbCheckout.uSync.${{steps.gitversion.outputs.fullSemVer}}.nupkg --skip-duplicate --source https://nuget.pkg.github.com/umbhost/index.json --api-key ${{ github.token }}
        dotnet nuget push ./build.out/UmbCheckout.Stripe.uSync.${{steps.gitversion.outputs.fullSemVer}}.nupkg --skip-duplicate --source https://nuget.pkg.github.com/umbhost/index.json --api-key ${{ github.token }}
